only check for empty if the build tool thinks the build succeeded
git-svn-id: https://svn.macosforge.org/repository/darwinbuild/trunk@246 10a61168-4876-4dac-953b-31e694342555

diff --git a/darwinbuild/darwinbuild b/darwinbuild/darwinbuild
--- a/darwinbuild/darwinbuild
+++ b/darwinbuild/darwinbuild
@@ -775,10 +775,12 @@ else
 	fi
 fi
 
-IsDirectoryEmpty "$REAL_DSTROOT"
-if [ $? -eq 0 ]; then
-    echo "$REAL_DSTROOT is empty. Build verification failed." 1>&2
-    EXIT_STATUS=3
+if [ $EXIT_STATUS -eq 0 ]; then
+    IsDirectoryEmpty "$REAL_DSTROOT"
+    if [ $? -eq 0 ]; then
+	echo "$REAL_DSTROOT is empty. Build verification failed." 1>&2
+	EXIT_STATUS=3
+    fi
 fi
 
 
